apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5lwn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-5lwn@sha256:7cba273a10ccfa99f90ed9a9e27297400fec3dc50d51a7aa8ad60988a686dc2b
        name: my-nodejs
        resources: {}
status: {}
